# Generated by Django 3.1.1 on 2023-09-26 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='internal_1',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='internal_2',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='internal_3',
        ),
    ]
