# Generated by Django 3.1.1 on 2023-09-28 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_areaofimprovement'),
    ]

    operations = [
        migrations.AddField(
            model_name='areaofimprovement',
            name='staff',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main_app.staff'),
        ),
    ]
