# Generated by Django 3.1.1 on 2023-09-28 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_areaofimprovement_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='areaofimprovement',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.staff'),
        ),
    ]
