# Generated by Django 3.1.1 on 2023-09-28 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_areaofimprovement_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='areaofimprovement',
            name='staff',
        ),
    ]
