# Generated by Django 3.1.1 on 2023-10-04 06:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_remove_areaofimprovement_staff'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(code='invalid_name', message='Enter a valid name (letters, spaces, hyphens, and apostrophes only).', regex="^[a-zA-Z\\s\\'-]+$")])),
                ('last_name', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(code='invalid_name', message='Enter a valid name (letters, spaces, hyphens, and apostrophes only).', regex="^[a-zA-Z\\s\\'-]+$")])),
            ],
        ),
    ]
