# Generated by Django 3.1.1 on 2023-10-04 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_mymodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyModel',
        ),
    ]
