# Generated by Django 3.1.1 on 2024-04-05 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_delete_mymodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='CroResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test', models.FloatField(default=0)),
                ('exam', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='FeedbackCro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.TextField()),
                ('reply', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='LeaveReportCro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=60)),
                ('message', models.TextField()),
                ('status', models.SmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='NotificationCro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='leavereportstudent',
            name='student',
        ),
        migrations.RemoveField(
            model_name='notificationstudent',
            name='student',
        ),
        migrations.RemoveField(
            model_name='studentresult',
            name='student',
        ),
        migrations.RemoveField(
            model_name='studentresult',
            name='subject',
        ),
        migrations.RenameField(
            model_name='areaofimprovement',
            old_name='student',
            new_name='cro',
        ),
        migrations.RenameField(
            model_name='attendancereport',
            old_name='student',
            new_name='cro',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[(1, 'HOD'), (2, 'Staff'), (3, 'Cro')], default=1, max_length=1),
        ),
        migrations.RenameModel(
            old_name='Student',
            new_name='Cro',
        ),
        migrations.DeleteModel(
            name='FeedbackStudent',
        ),
        migrations.DeleteModel(
            name='LeaveReportStudent',
        ),
        migrations.DeleteModel(
            name='NotificationStudent',
        ),
        migrations.DeleteModel(
            name='StudentResult',
        ),
        migrations.AddField(
            model_name='notificationcro',
            name='cro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.cro'),
        ),
        migrations.AddField(
            model_name='leavereportcro',
            name='cro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.cro'),
        ),
        migrations.AddField(
            model_name='feedbackcro',
            name='cro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.cro'),
        ),
        migrations.AddField(
            model_name='croresult',
            name='cro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.cro'),
        ),
        migrations.AddField(
            model_name='croresult',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.subject'),
        ),
    ]
