# Generated by Django 5.0.6 on 2024-06-30 10:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0013_auto_20240630_1408'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fin_year', models.IntegerField(help_text='Use the format YYYY', validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2024)])),
                ('category', models.CharField(choices=[('walkin', 'Walkin'), ('register', 'Register'), ('all', 'All')], max_length=20)),
                ('sales_person', models.CharField(choices=[('sheela', 'Sheela'), ('saranya', 'Saranya'), ('jeba', 'Jeba'), ('bamila', 'Bamila'), ('rolisha', 'Rolisha')], max_length=20)),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
            ],
        ),
        migrations.AlterField(
            model_name='walkin',
            name='sales_person',
            field=models.CharField(choices=[('sheela', 'Sheela'), ('saranya', 'Saranya'), ('jeba', 'Jeba'), ('bamila', 'Bamila'), ('rolisha', 'Rolisha')], max_length=20),
        ),
    ]
