# Generated by Django 5.0.6 on 2024-06-30 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0014_report_alter_walkin_sales_person'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='fin_year',
            new_name='financial_year',
        ),
    ]
