# Generated by Django 5.0.6 on 2024-06-30 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0015_rename_fin_year_report_financial_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='financial_year',
            field=models.IntegerField(choices=[('2021', '2022'), ('2022', '2023')], max_length=100),
        ),
    ]
