# Generated by Django 5.0.6 on 2024-06-30 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0016_alter_report_financial_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectionReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('financial_year', models.IntegerField(choices=[('2021-2022', '2022-2023'), ('2023-2024', '2024-2025'), ('2025-2026', '2026-2027'), ('2027-2028', '2028-2029'), ('2029-2030', '2030-2031')], max_length=100)),
                ('sales_person', models.CharField(choices=[('sheela', 'Sheela'), ('saranya', 'Saranya'), ('jeba', 'Jeba'), ('bamila', 'Bamila'), ('rolisha', 'Rolisha')], max_length=20)),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='PendingPaymentReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('financial_year', models.IntegerField(choices=[('2021-2022', '2022-2023'), ('2023-2024', '2024-2025'), ('2025-2026', '2026-2027'), ('2027-2028', '2028-2029'), ('2029-2030', '2030-2031')], max_length=100)),
                ('sales_person', models.CharField(choices=[('sheela', 'Sheela'), ('saranya', 'Saranya'), ('jeba', 'Jeba'), ('bamila', 'Bamila'), ('rolisha', 'Rolisha')], max_length=20)),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='ReferenceReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('financial_year', models.IntegerField(choices=[('2021-2022', '2022-2023'), ('2023-2024', '2024-2025'), ('2025-2026', '2026-2027'), ('2027-2028', '2028-2029'), ('2029-2030', '2030-2031')], max_length=100)),
                ('sales_person', models.CharField(choices=[('sheela', 'Sheela'), ('saranya', 'Saranya'), ('jeba', 'Jeba'), ('bamila', 'Bamila'), ('rolisha', 'Rolisha')], max_length=20)),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='RegistrationReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('financial_year', models.IntegerField(choices=[('2021-2022', '2022-2023'), ('2023-2024', '2024-2025'), ('2025-2026', '2026-2027'), ('2027-2028', '2028-2029'), ('2029-2030', '2030-2031')], max_length=100)),
                ('category', models.CharField(choices=[('walkin', 'Walkin'), ('register', 'Register'), ('all', 'All')], max_length=20)),
                ('sales_person', models.CharField(choices=[('sheela', 'Sheela'), ('saranya', 'Saranya'), ('jeba', 'Jeba'), ('bamila', 'Bamila'), ('rolisha', 'Rolisha')], max_length=20)),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='WalkinReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('financial_year', models.IntegerField(choices=[('2021-2022', '2022-2023'), ('2023-2024', '2024-2025'), ('2025-2026', '2026-2027'), ('2027-2028', '2028-2029'), ('2029-2030', '2030-2031')], max_length=100)),
                ('category', models.CharField(choices=[('walkin', 'Walkin'), ('register', 'Register'), ('all', 'All')], max_length=20)),
                ('sales_person', models.CharField(choices=[('sheela', 'Sheela'), ('saranya', 'Saranya'), ('jeba', 'Jeba'), ('bamila', 'Bamila'), ('rolisha', 'Rolisha')], max_length=20)),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name='Report',
        ),
    ]
